# Generated by Django 3.0.4 on 2020-10-30 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPI_Colaborador', models.CharField(max_length=16)),
                ('correo_colaborador', models.CharField(max_length=50)),
                ('estado_colaborador', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_min_stock', models.PositiveIntegerField()),
                ('estado_producto', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('descripcion_codigo_lote', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='perfiles_colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=20)),
                ('descripcion_perfil', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=60)),
                ('apellido_persona', models.CharField(max_length=60)),
                ('direccion_persona', models.TextField()),
                ('nit_persona', models.CharField(max_length=10, null=True, unique=True)),
                ('telefono_persona', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='prefijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_prefijo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='regimens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_regimen', models.CharField(max_length=20)),
                ('impuesto_regimen', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='unidad_medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_unidad_medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='telefonos_personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=8)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.personas')),
            ],
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=40)),
                ('direccion_sucursal', models.TextField()),
                ('correo_sucursal', models.CharField(max_length=50)),
                ('nit_sucursal', models.CharField(max_length=10, unique=True)),
                ('telefono_sucursal', models.CharField(max_length=10)),
                ('persona_encargada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.personas')),
                ('prefijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.prefijos')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.regimens')),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=60)),
                ('direccion_proveedor', models.TextField()),
                ('telefono_proveedor', models.CharField(max_length=8)),
                ('nit_proveedor', models.CharField(max_length=10, unique=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('persona_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.personas')),
                ('prefijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.prefijos')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.PositiveIntegerField()),
                ('nombre_producto', models.TextField()),
                ('descripcion_producto', models.TextField()),
                ('detalle_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.detalle_productos')),
                ('prefijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFactInv.prefijos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='encabezado_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.personas')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.colaboradores')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.sucursales')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='detalle_productos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appFactInv.marcas'),
        ),
        migrations.AddField(
            model_name='detalle_productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.proveedores'),
        ),
        migrations.AddField(
            model_name='detalle_productos',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.unidad_medidas'),
        ),
        migrations.CreateModel(
            name='detalle_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.encabezado_factura')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='perfil_colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.perfiles_colaboradores'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.personas'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='prefijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.prefijos'),
        ),
    ]
