# Generated by Django 3.0.4 on 2020-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0002_auto_20201031_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado_factura',
            name='iva',
        ),
    ]
